# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc10c5696ace92aa74ab0166c30a4b8c2b5da14a1544ddaae41e0e7dd36f041787c7df3069d04defd9bba321e5a9267695a65459c5fecc92a02ac5bfabe925dd

test:
  secret_key_base: 5169f6ec4aa812a706e0dc765bf5f1bc540211a70f74edcc4288946da11d537b411fe0d10693679e148e6c9744c05c2c8efeb418418efb2a230f0923cba52078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
